server:
  port: 8000
  servlet:
    context-path: /order-service

logging:
  level:
    org:
      springframework:
        cloud: error

spring:
  application:
    name: order-service

  main:
    banner-mode: off

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.globally_quoted_identifiers: true

  config:
    import: "optional:kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: refresh
      config:
        fail-fast: true
      secrets:
        fail-fast: true
    function:
      definition:
    stream:
      bindings:
        order-out-0:
          destination: order
      kafka:
        bindings:
          order:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
